const siteUrl = 'https://hls.mobissa.ru/';
// const siteUrl = 'https://hls-backend-stage.herokuapp.com/';
//const siteUrl = 'http://213.183.48.100:3000/';
const apiUri = '${siteUrl}graphql';
const apiTokenKey = 'Client-Token';
const apiTokenValue = 'WcbKFUnrAteA3YyajbK8c68839j7TXXq';
const apiHeaders = {
  apiTokenKey: apiTokenValue,
  'Content-Type': 'application/json'
};
const authTokenKey = 'Auth-Token';

// http path

const avatarUploadPath = 'upload';

const oneSignalAppId = '08f76ad3-3c2d-405a-8492-c199ff2fe398';

// graphql types

const pageInfoFields = ''
    '{'
    'endCursor '
    'hasNextPage'
    '}';

const userCommonFields = ''
    'todaySchedule $scheduleFields'
    'data '
    '{'
    'name '
    'age '
    'birthDate '
    'gender '
    'weight '
    'height'
    '} '
    'dailyRating '
    '{'
    'activity '
    'eating '
    'mode'
    '} '
    'id '
    'photoUrl '
    'email '
    'phoneNumber '
    'timezone';

const userHealthLevelField = '{'
    'percent '
//'value'
    '}';

const desiredFoodsField = '{'
    'title '
    '}';

const userFields = '{'
    '$userCommonFields '
    'weeklyTrainings '
    'progress '
    '{'
    'agesDiagram '
    'goal '
    'health '
    '{'
    'adaptiveCapacity $userHealthLevelField '
    'functionalityIndex $userHealthLevelField '
    'historyValues '
    '{'
    'avgRating '
    'formulasRating '
    'hlsApplication '
    'createdAt'
    '} '
    'hlsApplication '
    'queteletIndex $userHealthLevelField '
    'robinsonIndex $userHealthLevelField '
    'rufierProbe $userHealthLevelField '
    'debugInfo'
    '} '
    'macrocycle '
    'microcycle '
    '{'
    'number '
    'completedTrainings '
    'totalTrainings'
    '}'
    '} '
    'chatBotDialogs '
    '{'
    'id '
    'name '
    'status'
    '} '
    'desiredFoods $desiredFoodsField'
    '}';

const uploadFields = '{'
//'blobId '
//'headers '
    'signedBlobId '
    'url'
    '}';

const chatBotDialogCommonFields =
//'chatBot $chatBotFields '
    'id '
    'name '
    'status '
    'result';

const chatBotDialogHistoryFields = '{'
    '$chatBotDialogCommonFields '
    'history $chatBotHistoryFields'
    '}';

const chatBotDialogFields = '{'
    '$chatBotDialogCommonFields '
    'user $userFields'
    '}';

const chatBotFields = '{'
    ''
    '}';

const chatBotHistoryFields = '{'
    'order '
    'question '
    'answer'
    '}';

const chatCardFields = '{'
    'key '
    'addons '
    'questionType '
    'questions '
    'answers '
    'style '
    'results'
    '}';

const postFields = '{'
    'id '
    'title '
    'content '
    'imageUrl '
    'kind '
    'isHalf '
//'isFavourite '
    'publishedAt '
    'stories '
    '{'
    'id '
    'imageUrl '
    'content'
    '}'
    'videoDuration '
    'videoUrl'
    '}';

const iconFields = 'icon '
    '{'
    'url'
    '}';

const foodCategoryGeneral = 'id '
    'title '
    '$iconFields';

const foodFiltersListFields = '{'
    'key '
    'title '
    'section '
    'values '
//'filters'
    '}';

const foodCategoryListFields = '{'
    '$foodCategoryGeneral'
    '}';

const foodCategoryFields = '{'
    '$foodCategoryGeneral'
//'parentCategory $foodCategoryListFields'
    'subcategories $foodSubcategoryFields'
    'foods $foodFields'
    '}';

const foodSubcategoryFields = '{'
    '$foodCategoryGeneral'
//'parentCategory $foodCategoryListFields'
    'subcategories $foodSubcategory2Fields'
    'foods $foodFields'
    '}';

const foodSubcategory2Fields = '{'
    '$foodCategoryGeneral'
//'parentCategory $foodCategoryListFields'
    'subcategories $foodSubcategory3Fields'
    'foods $foodFields'
    '}';

const foodSubcategory3Fields = '{'
    '$foodCategoryGeneral'
//'parentCategory $foodCategoryListFields'
    'foods $foodFields'
    '}';

const foodFields = '{'
    'id '
    'title '
    '$iconFields '
// 'structure '
// '{'
//   'key '
//   'quantity '
//   'section '
//   'title '
//   'unit '
// '} '
    'foodCategory $foodCategoryListFields '
    'championOn'
    '}';

const foodFullFields = '{'
    'id '
    'title '
    '$iconFields '
    'structure '
    '{'
    'key '
    'quantity '
    'section '
    'title '
    'unit '
    '} '
    'foodCategory $foodCategoryListFields '
    'championOn'
    '}';

const scheduleFields = '{'
    'id '
    'items $scheduleItemFields '
    'yesterdayAsleepTime'
    '}';

const scheduleItemFields = '{'
    'id '
    'kind '
    'plannedAt'
    '}';

const trainingCategoryFields = '{'
    'title '
    '$iconFields '
    'subcategories $trainingSubcategory1Fields'
    'trainings $trainingFields'
    '}';

const trainingSubcategory1Fields = '{'
    'title '
    '$iconFields '
    'subcategories $trainingSubcategory2Fields '
    'trainings $trainingFields'
    '}';

const trainingSubcategory2Fields = '{'
    'title '
    '$iconFields '
    'trainings $trainingFields'
    '}';

const trainingFields = '{'
    'id '
    'title '
    '$iconFields '
    'description '
    'kind '
// 'videoUrl '
// 'inputData '
// '{'
//   'title '
//   'unit '
//   'inputType '
//   'max '
//   'min '
//   'step'
// '} '
// 'pulseZones '
// '{'
//   'color '
//   'title '
//   'description '
//   'heartRate '
//   'isRecommended'
// '}'
    '}';

const icon = '{'
    'url '
    '} ';

const trainingEquipments = '{'
    'icon $icon '
    '} ';

const trainingDetailFields = '{'
    'id '
    'title '
    'trainingEquipments $trainingEquipments '
    '$iconFields '
    'description '
    'kind '
    'videoUrl '
    'thumbnailUrl '
    'inputData '
    '{'
    'title '
    'unit '
    'inputType '
    'max '
    'min '
    'step'
    '} '
    'pulseZones '
    '{'
    'color '
    'title '
    'description '
    'heartRate '
    'isRecommended'
    '} '
    'videoPulseCheckTime'
    '}';

// query

const currentUserQuery = 'query '
    '{'
    'currentUser $userFields'
    '}';

const chatHistoryQuery = 'query '
    '{'
    'currentUser '
    '{'
    'chatBotDialogs $chatBotDialogHistoryFields'
    '}'
    '}';

const statsQuery = 'query '
    '{'
    'currentUser '
    '{'
    'dailyRating '
    '{'
    'activity'
    'eating'
    'mode'
    '}'
    '}'
    '}';

const dailyRatingTipQuery = 'query '
    '('
    '\$type: DailyRatingTipKind'
    ')'
    '{'
    'dailyRatingTip '
    '('
    'kind: \$type'
    ') '
    '{'
    'text'
    '}'
    '}';

const postsQuery = 'query '
    '{'
    'posts '
    '{'
    'nodes $postFields '
    'pageInfo '
    '{'
    'endCursor '
    'hasNextPage'
    '}'
    '}'
    '}';

const foodCategoriesQuery = 'query '
    '{'
    'foodCategories $foodCategoryListFields'
    '}';

const foodFilterQuery = 'query '
    '{'
    'foodFiltersList '
    '$foodFiltersListFields'
    '}';

const foodCategoryQuery = 'query '
    '('
    '\$id: ID!'
    ')'
    '{'
    'foodCategory '
    '('
    'id: \$id'
    ') '
    '$foodCategoryFields'
    '}';

const foodQuery = 'query '
    '('
    '\$id: ID!'
    ')'
    '{'
    'food '
    '('
    'id: \$id'
    ') '
    '$foodFullFields'
    '}';

const foodsQuery = 'query '
    '('
    '\$search: String '
    '\$filters: Json '
    '\$sort: FoodSortInput '
    '\$first: Int '
    '\$after: String'
    ')'
    '{'
    'foods '
    '('
    'search: \$search '
    'filters: \$filters '
    'sort: \$sort '
    'first: \$first '
    'after: \$after'
    ') '
    '{'
    'nodes $foodFullFields '
    'pageInfo $pageInfoFields'
    '}'
    '}';

const trainingCategoriesQuery = 'query '
    '{'
    'trainingCategories '
    '{'
    'nodes $trainingCategoryFields'
    '}'
    '}';

const trainingsQuery = 'query '
    '('
    '\$search: String '
    '\$first: Int '
    '\$after: String'
    ')'
    '{'
    'trainings '
    '('
    'filter: {titleCont: \$search}'
    'first: \$first '
    'after: \$after'
    ') '
    '{'
    'nodes $trainingFields '
    'pageInfo $pageInfoFields'
    '}'
    '}';

const trainingQuery = 'query '
    '('
    '\$id: ID!'
    ')'
    '{'
    'training '
    '('
    'id: \$id'
    ') $trainingDetailFields'
    '}';

// schedule queries
const dailyRating = '{'
    'mode '
    'activity '
    'eating '
    '} ';

const kind = '{'
    'kind '
    'plannedAt '
    '} ';

const structure = '{'
    'key '
    'quantity '
    'section '
    'title '
    'unit '
    '} ';

const food = '{'
    'title '
    'portion '
    'structure $structure'
    '} ';

const scheduleEatings = '{'
    'scheduleItem $kind'
    'food $food'
    '} ';

const foodComponent = '{'
    'title '
    'unit '
    'section '
    '} ';

const consumedFoodComponents = '{'
    'lowerLimit '
    'value '
    'upperLimit '
    'foodComponent $foodComponent'
    '} ';

const inputData = '{'
    'title '
    'inputType '
    'max '
    'min '
    'step '
    'unit '
    '} ';

const trainingCategory = '{'
    'title '
    '}';

const training = '{'
    'title '
    'inputData $inputData '
    'trainingCategory $trainingCategory '
    '} ';

const scheduleTrainings = '{'
    'inputType '
    'inputValue '
    'training $training'
    '} ';

const primaryStats = '{'
    'energyValue '
    'nutrients '
    'water '
    '} ';

const component = '{'
    'title '
    '} ';
const stats = '{'
    'limit '
    'value '
    'component $component '
    '} ';

const consumedComponentsPerEating = '{'
    'stats $stats '
'scheduleItem'
    '{'
    'kind '
    'plannedAt '
    '} '
    '} ';

const foodRating = '{'
    'consumedComponentsPerEating $consumedComponentsPerEating'
    'consumedComponents $consumedFoodComponents'
    'primaryStats $primaryStats '
    '} ';

// const scheduleRating = 'query '
//     '('
//     '\$fromDate: Date '
//     '\$toDate: Date'
//     ') '
//     '{'
//     'schedules'
//     '('
//     'fromDate: \$fromDate '
//     'toDate: \$toDate'
//     ') '
//     '{'
//     'scheduleDate '
//     'dailyRating $dailyRating'
//     '}'
//     '}';

const activityRating = '{'
    'activeLeisureRating '
    'motionRating '
    'trainingRating '
    '} ';

const schedule = 'query '
    '('
    '\$id: ID! '
    ') '
    '{'
    'schedule'
    '('
    'id: \$id '
    ') '
    '{'
// 'scheduleDate '
//     'yesterdayAsleepTime '
    'sleepDuration '
    'sleepReport '
    'foodRating $foodRating'
// 'dailyRating $dailyRating'
    'activityRating $activityRating '
    'scheduleTrainings $scheduleTrainings '
    'scheduleEatings $scheduleEatings'
    '}'
    '}';

const calendarQuery = 'query '
// '('
// '\$fromDate: Date '
// '\$toDate: Date'
// ') '
    '{'
    'schedules'
// '('
// 'fromDate: \$fromDate '
// 'toDate: \$toDate'
// ') '
    '{'
    'id '
    'scheduleDate '
    'dailyRating $dailyRating'
    '}'
    '}';

// mutations

const usersSetTimezoneMutation = 'mutation'
    '('
    '\$timezone: String!'
    ') '
    '{'
    'usersSetTimezone'
    '('
    'timezone: \$timezone'
    ') '
    '{'
    'user '
    '{'
    'id'
    '}'
    '}'
    '}';

const authSignInMutation = 'mutation'
    '('
    '\$login: String! '
    '\$password: String!'
    ') '
    '{'
    'authSignIn'
    '('
    'email: \$login '
    'password: \$password '
    'admin: false'
    ') '
    '{'
    'authToken '
    'user $userFields'
    '}'
    '}';

const authSignOutMutation = 'mutation '
    '{'
    'authSignOut'
    '{'
    'status'
    '}'
    '}';

const authSendOtpMutation = 'mutation '
    '('
    '\$phone: String!'
    ') '
    '{'
    'authSendOtp'
    '('
    'phoneNumber: \$phone'
    ') '
    '{'
    'status'
    '}'
    '}';

const authVerifyOtpMutation = 'mutation'
    '('
    '\$code: String! '
    '\$phone: String!'
    ') '
    '{'
    'authVerifyOtp'
    '('
    'code: \$code '
    'phoneNumber: \$phone'
    ') '
    '{'
    'authToken '
    'user $userFields'
    '}'
    '}';

const chatBotDialogStartMutation = 'mutation'
    '('
    '\$name: String!'
    ') '
    '{'
    'chatBotDialogStart'
    '('
    'name: \$name'
    ') '
    '{'
    'dialogId '
    'nextCard $chatCardFields'
    '}'
    '}';

const chatBotDialogResumeMutation = 'mutation'
    '('
    '\$dialogId: ID!'
    ') '
    '{'
    'chatBotDialogResume'
    '('
    'dialogId: \$dialogId'
    ') '
    '{'
    'dialog $chatBotDialogHistoryFields '
    'nextCard $chatCardFields'
    '}'
    '}';

const chatBotDialogContinueMutation = 'mutation'
    '('
    '\$dialogId: ID! '
    '\$key: ID! '
    '\$values: [String!]!'
    ') '
    '{'
    'chatBotDialogContinue'
    '('
    'dialogId: \$dialogId '
    'answer: '
    '{'
    'key: \$key '
    'values: \$values'
    '}'
    ') '
    '{'
    'dialog $chatBotDialogFields '
    'nextCard $chatCardFields'
    '}'
    '}';

const schedulesCreateMutation = 'mutation'
    '('
    '\$asleepTime: String! '
    '\$wakeupTime: String! '
    '\$trainingTime: String'
    ') '
    '{'
    'schedulesCreate'
    '('
    'yesterdayAsleepTime: \$asleepTime '
    'wakeUpTime: \$wakeupTime '
    'trainingTime: \$trainingTime'
    ') '
    '{'
    'schedule $scheduleFields'
    '}'
    '}';

const desiredFoodsCreateMutation = 'mutation'
    '('
    '\$title: String!'
    ') '
    '{'
    'desiredFoodsCreate'
    '('
    'title: \$title'
    ') '
    '{'
    'desiredFood '
    '{'
    'user '
    '{'
    'desiredFoods $desiredFoodsField'
    '}'
    '}'
    '}'
    '}';

const scheduleEatingsCreateMutation = 'mutation'
    '('
    '\$scheduleId: ID! '
    '\$scheduleItemId: ID '
    '\$foodId: ID! '
    '\$portion: Float!'
    ') '
    '{'
    'schedulesEatingsCreate'
    '('
    'scheduleId: \$scheduleId '
    'itemId: \$scheduleItemId '
    'foodId: \$foodId '
    'portion: \$portion'
    ') '
    '{'
    'scheduleEating '
    '{'
    'id'
    '}'
    '}'
    '}';

const scheduleTrainingsCreateMutation = 'mutation'
    '('
    '\$scheduleId: ID! '
    '\$exerciseId: ID! '
    '\$type: TrainingInputType! '
    '\$value: Int!'
    '\$data: Json'
    ') '
    '{'
    'scheduleTrainingsCreate'
    '('
    'scheduleId: \$scheduleId '
    'trainingId: \$exerciseId '
    'inputType: \$type '
    'inputValue: \$value '
    'data: \$data'
    ') '
    '{'
    'scheduleTraining '
    '{'
    'id'
    '}'
    '}'
    '}';

const usersToggleWeeklyTrainingMutation = 'mutation'
    '('
    '\$day: Int!'
    ') '
    '{'
    'usersToggleWeeklyTraining'
    '('
    'weekDay: \$day'
    ') '
    '{'
    'user $userFields'
    '}'
    '}';

const usersUpdateProfileMutation = 'mutation'
    '('
    '\$name: String '
//'\$gender: ID '
    '\$birthDate: Date '
    '\$height: Int '
    '\$weight: Int'
    ') '
    '{'
    'usersUpdateProfile'
    '('
    'updatedParams: '
    '{'
    'name: \$name '
//'gender: \$gender '
    'birthDate: \$birthDate '
    'height: \$height '
    'weight: \$weight'
    '}'
    ') '
    '{'
    'user $userFields'
    '}'
    '}';

const createDirectUploadMutation = 'mutation'
    '('
    '\$filename: String! '
    '\$byteSize: Int! '
    '\$checksum: String! '
    '\$contentType: String!'
    ') '
    '{'
    'createDirectUpload'
    '('
    'input: '
    '{'
    'filename: \$filename '
    'byteSize: \$byteSize '
    'checksum: \$checksum '
    'contentType: \$contentType'
    '}'
    ') '
    '{'
    'directUpload $uploadFields'
    '}'
    '}';
